NB. libcurl in J
NB. 
require 'dll'

NB. search '---- CODE' to get to the start of actual code
NB. ---- CONSTANTS ----

NB. #define CURLOPTTYPE_LONG          0
NB. #define CURLOPTTYPE_OBJECTPOINT   10000
NB. #define CURLOPTTYPE_FUNCTIONPOINT 20000
NB. #define CURLOPTTYPE_OFF_T         30000
NB. #define CURLOPTTYPE_BLOB          40000

NB. #define CURL_GLOBAL_SSL (1<<0) /* no purpose since 7.57.0 */
NB. #define CURL_GLOBAL_WIN32 (1<<1)
NB. #define CURL_GLOBAL_ALL (CURL_GLOBAL_SSL|CURL_GLOBAL_WIN32)
NB. #define CURL_GLOBAL_NOTHING 0
NB. #define CURL_GLOBAL_DEFAULT CURL_GLOBAL_ALL 
NB. #define CURL_GLOBAL_ACK_EINTR (1<<2)
CURL_GLOBAL_DEFAULT =: 3
CURL_GLOBAL_NOTHING =: 0
CURL_GLOBAL_ALL =: 3
CURL_GLOBAL_SSL =: 1
CURL_GLOBAL_WIN32 =: 2
CURL_GLOBAL_ACK_EINTR =: 4

NB. CURLOPT definitions
NB. the following were some hand picked constants
NB. CURLOPT_URL=: 10002
NB. CURLOPT_FILE=: 10001
NB. CURLOPT_HTTPHEADER=: 10023
NB. CURLOPT_POSTFIELDS=: 10015
NB. CURLOPT_WRITEFUNCTION=: 20011
NB. CURLOPT_WRITEDATA=: 10001
NB. CURLOPT_PORT=: 3
NB. CURLOPT_PROXY=: 10004
NB. CURLOPT_USERPWD=: 10005
NB. CURLOPT_PROXYUSERPWD=: 10006
NB. CURLOPT_HEADER=: 42
NB. CURLOPT_VERBOSE=: 41


NB. These constants were found by running a C program to create the 
NB. J assignment statements based on the libcurl library on the Mac
CURLOPT_WRITEDATA =: 10001
CURLOPT_URL =: 10002
CURLOPT_PORT =: 3
CURLOPT_PROXY =: 10004
CURLOPT_USERPWD =: 10005
CURLOPT_PROXYUSERPWD =: 10006
CURLOPT_RANGE =: 10007
CURLOPT_READDATA =: 10009
CURLOPT_ERRORBUFFER =: 10010
CURLOPT_WRITEFUNCTION =: 20011
CURLOPT_READFUNCTION =: 20012
CURLOPT_TIMEOUT =: 13
CURLOPT_INFILESIZE =: 14
CURLOPT_POSTFIELDS =: 10015
CURLOPT_REFERER =: 10016
CURLOPT_FTPPORT =: 10017
CURLOPT_USERAGENT =: 10018
CURLOPT_LOW_SPEED_LIMIT =: 19
CURLOPT_LOW_SPEED_TIME =: 20
CURLOPT_RESUME_FROM =: 21
CURLOPT_COOKIE =: 10022
CURLOPT_HTTPHEADER =: 10023
CURLOPT_HTTPPOST =: 10024
CURLOPT_SSLCERT =: 10025
CURLOPT_KEYPASSWD =: 10026
CURLOPT_CRLF =: 27
CURLOPT_QUOTE =: 10028
CURLOPT_HEADERDATA =: 10029
CURLOPT_COOKIEFILE =: 10031
CURLOPT_SSLVERSION =: 32
CURLOPT_TIMECONDITION =: 33
CURLOPT_TIMEVALUE =: 34
CURLOPT_CUSTOMREQUEST =: 10036
CURLOPT_STDERR =: 10037
CURLOPT_POSTQUOTE =: 10039
CURLOPT_VERBOSE =: 41
CURLOPT_HEADER =: 42
CURLOPT_NOPROGRESS =: 43
CURLOPT_NOBODY =: 44
CURLOPT_FAILONERROR =: 45
CURLOPT_UPLOAD =: 46
CURLOPT_POST =: 47
CURLOPT_DIRLISTONLY =: 48
CURLOPT_APPEND =: 50
CURLOPT_NETRC =: 51
CURLOPT_FOLLOWLOCATION =: 52
CURLOPT_TRANSFERTEXT =: 53
CURLOPT_PUT =: 54
CURLOPT_PROGRESSFUNCTION =: 20056
CURLOPT_XFERINFODATA =: 10057
CURLOPT_AUTOREFERER =: 58
CURLOPT_PROXYPORT =: 59
CURLOPT_POSTFIELDSIZE =: 60
CURLOPT_HTTPPROXYTUNNEL =: 61
CURLOPT_INTERFACE =: 10062
CURLOPT_KRBLEVEL =: 10063
CURLOPT_SSL_VERIFYPEER =: 64
CURLOPT_CAINFO =: 10065
CURLOPT_MAXREDIRS =: 68
CURLOPT_FILETIME =: 69
CURLOPT_TELNETOPTIONS =: 10070
CURLOPT_MAXCONNECTS =: 71
CURLOPT_FRESH_CONNECT =: 74
CURLOPT_FORBID_REUSE =: 75
CURLOPT_RANDOM_FILE =: 10076
CURLOPT_EGDSOCKET =: 10077
CURLOPT_CONNECTTIMEOUT =: 78
CURLOPT_HEADERFUNCTION =: 20079
CURLOPT_HTTPGET =: 80
CURLOPT_SSL_VERIFYHOST =: 81
CURLOPT_COOKIEJAR =: 10082
CURLOPT_SSL_CIPHER_LIST =: 10083
CURLOPT_HTTP_VERSION =: 84
CURLOPT_FTP_USE_EPSV =: 85
CURLOPT_SSLCERTTYPE =: 10086
CURLOPT_SSLKEY =: 10087
CURLOPT_SSLKEYTYPE =: 10088
CURLOPT_SSLENGINE =: 10089
CURLOPT_SSLENGINE_DEFAULT =: 90
CURLOPT_DNS_USE_GLOBAL_CACHE =: 91
CURLOPT_DNS_CACHE_TIMEOUT =: 92
CURLOPT_PREQUOTE =: 10093
CURLOPT_DEBUGFUNCTION =: 20094
CURLOPT_DEBUGDATA =: 10095
CURLOPT_COOKIESESSION =: 96
CURLOPT_CAPATH =: 10097
CURLOPT_BUFFERSIZE =: 98
CURLOPT_NOSIGNAL =: 99
CURLOPT_SHARE =: 10100
CURLOPT_PROXYTYPE =: 101
CURLOPT_ACCEPT_ENCODING =: 10102
CURLOPT_PRIVATE =: 10103
CURLOPT_HTTP200ALIASES =: 10104
CURLOPT_UNRESTRICTED_AUTH =: 105
CURLOPT_FTP_USE_EPRT =: 106
CURLOPT_HTTPAUTH =: 107
CURLOPT_SSL_CTX_FUNCTION =: 20108
CURLOPT_SSL_CTX_DATA =: 10109
CURLOPT_FTP_CREATE_MISSING_DIRS =: 110
CURLOPT_PROXYAUTH =: 111
CURLOPT_SERVER_RESPONSE_TIMEOUT =: 112
CURLOPT_IPRESOLVE =: 113
CURLOPT_MAXFILESIZE =: 114
CURLOPT_INFILESIZE_LARGE =: 30115
CURLOPT_RESUME_FROM_LARGE =: 30116
CURLOPT_MAXFILESIZE_LARGE =: 30117
CURLOPT_NETRC_FILE =: 10118
CURLOPT_USE_SSL =: 119
CURLOPT_POSTFIELDSIZE_LARGE =: 30120
CURLOPT_TCP_NODELAY =: 121
CURLOPT_FTPSSLAUTH =: 129
CURLOPT_IOCTLFUNCTION =: 20130
CURLOPT_IOCTLDATA =: 10131
CURLOPT_FTP_ACCOUNT =: 10134
CURLOPT_COOKIELIST =: 10135
CURLOPT_IGNORE_CONTENT_LENGTH =: 136
CURLOPT_FTP_SKIP_PASV_IP =: 137
CURLOPT_FTP_FILEMETHOD =: 138
CURLOPT_LOCALPORT =: 139
CURLOPT_LOCALPORTRANGE =: 140
CURLOPT_CONNECT_ONLY =: 141
CURLOPT_CONV_FROM_NETWORK_FUNCTION =: 20142
CURLOPT_CONV_TO_NETWORK_FUNCTION =: 20143
CURLOPT_CONV_FROM_UTF8_FUNCTION =: 20144
CURLOPT_MAX_SEND_SPEED_LARGE =: 30145
CURLOPT_MAX_RECV_SPEED_LARGE =: 30146
CURLOPT_FTP_ALTERNATIVE_TO_USER =: 10147
CURLOPT_SOCKOPTFUNCTION =: 20148
CURLOPT_SOCKOPTDATA =: 10149
CURLOPT_SSL_SESSIONID_CACHE =: 150
CURLOPT_SSH_AUTH_TYPES =: 151
CURLOPT_SSH_PUBLIC_KEYFILE =: 10152
CURLOPT_SSH_PRIVATE_KEYFILE =: 10153
CURLOPT_FTP_SSL_CCC =: 154
CURLOPT_TIMEOUT_MS =: 155
CURLOPT_CONNECTTIMEOUT_MS =: 156
CURLOPT_HTTP_TRANSFER_DECODING =: 157
CURLOPT_HTTP_CONTENT_DECODING =: 158
CURLOPT_NEW_FILE_PERMS =: 159
CURLOPT_NEW_DIRECTORY_PERMS =: 160
CURLOPT_POSTREDIR =: 161
CURLOPT_SSH_HOST_PUBLIC_KEY_MD5 =: 10162
CURLOPT_OPENSOCKETFUNCTION =: 20163
CURLOPT_OPENSOCKETDATA =: 10164
CURLOPT_COPYPOSTFIELDS =: 10165
CURLOPT_PROXY_TRANSFER_MODE =: 166
CURLOPT_SEEKFUNCTION =: 20167
CURLOPT_SEEKDATA =: 10168
CURLOPT_CRLFILE =: 10169
CURLOPT_ISSUERCERT =: 10170
CURLOPT_ADDRESS_SCOPE =: 171
CURLOPT_CERTINFO =: 172
CURLOPT_USERNAME =: 10173
CURLOPT_PASSWORD =: 10174
CURLOPT_PROXYUSERNAME =: 10175
CURLOPT_PROXYPASSWORD =: 10176
CURLOPT_NOPROXY =: 10177
CURLOPT_TFTP_BLKSIZE =: 178
CURLOPT_SOCKS5_GSSAPI_SERVICE =: 10179
CURLOPT_SOCKS5_GSSAPI_NEC =: 180
CURLOPT_PROTOCOLS =: 181
CURLOPT_REDIR_PROTOCOLS =: 182
CURLOPT_SSH_KNOWNHOSTS =: 10183
CURLOPT_SSH_KEYFUNCTION =: 20184
CURLOPT_SSH_KEYDATA =: 10185
CURLOPT_MAIL_FROM =: 10186
CURLOPT_MAIL_RCPT =: 10187
CURLOPT_FTP_USE_PRET =: 188
CURLOPT_RTSP_REQUEST =: 189
CURLOPT_RTSP_SESSION_ID =: 10190
CURLOPT_RTSP_STREAM_URI =: 10191
CURLOPT_RTSP_TRANSPORT =: 10192
CURLOPT_RTSP_CLIENT_CSEQ =: 193
CURLOPT_RTSP_SERVER_CSEQ =: 194
CURLOPT_INTERLEAVEDATA =: 10195
CURLOPT_INTERLEAVEFUNCTION =: 20196
CURLOPT_WILDCARDMATCH =: 197
CURLOPT_CHUNK_BGN_FUNCTION =: 20198
CURLOPT_CHUNK_END_FUNCTION =: 20199
CURLOPT_FNMATCH_FUNCTION =: 20200
CURLOPT_CHUNK_DATA =: 10201
CURLOPT_FNMATCH_DATA =: 10202
CURLOPT_RESOLVE =: 10203
CURLOPT_TLSAUTH_USERNAME =: 10204
CURLOPT_TLSAUTH_PASSWORD =: 10205
CURLOPT_TLSAUTH_TYPE =: 10206
CURLOPT_TRANSFER_ENCODING =: 207
CURLOPT_CLOSESOCKETFUNCTION =: 20208
CURLOPT_CLOSESOCKETDATA =: 10209
CURLOPT_GSSAPI_DELEGATION =: 210
CURLOPT_DNS_SERVERS =: 10211
CURLOPT_ACCEPTTIMEOUT_MS =: 212
CURLOPT_TCP_KEEPALIVE =: 213
CURLOPT_TCP_KEEPIDLE =: 214
CURLOPT_TCP_KEEPINTVL =: 215
CURLOPT_SSL_OPTIONS =: 216
CURLOPT_MAIL_AUTH =: 10217
CURLOPT_SASL_IR =: 218
CURLOPT_XFERINFOFUNCTION =: 20219
CURLOPT_XOAUTH2_BEARER =: 10220
CURLOPT_DNS_INTERFACE =: 10221
CURLOPT_DNS_LOCAL_IP4 =: 10222
CURLOPT_DNS_LOCAL_IP6 =: 10223
CURLOPT_LOGIN_OPTIONS =: 10224
CURLOPT_SSL_ENABLE_NPN =: 225
CURLOPT_SSL_ENABLE_ALPN =: 226
CURLOPT_EXPECT_100_TIMEOUT_MS =: 227
CURLOPT_PROXYHEADER =: 10228
CURLOPT_HEADEROPT =: 229
CURLOPT_PINNEDPUBLICKEY =: 10230
CURLOPT_UNIX_SOCKET_PATH =: 10231
CURLOPT_SSL_VERIFYSTATUS =: 232
CURLOPT_SSL_FALSESTART =: 233
CURLOPT_PATH_AS_IS =: 234
CURLOPT_PROXY_SERVICE_NAME =: 10235
CURLOPT_SERVICE_NAME =: 10236
CURLOPT_PIPEWAIT =: 237
CURLOPT_DEFAULT_PROTOCOL =: 10238
CURLOPT_STREAM_WEIGHT =: 239
CURLOPT_STREAM_DEPENDS =: 10240
CURLOPT_STREAM_DEPENDS_E =: 10241
CURLOPT_TFTP_NO_OPTIONS =: 242
CURLOPT_CONNECT_TO =: 10243
CURLOPT_TCP_FASTOPEN =: 244
CURLOPT_KEEP_SENDING_ON_ERROR =: 245
CURLOPT_PROXY_CAINFO =: 10246
CURLOPT_PROXY_CAPATH =: 10247
CURLOPT_PROXY_SSL_VERIFYPEER =: 248
CURLOPT_PROXY_SSL_VERIFYHOST =: 249
CURLOPT_PROXY_SSLVERSION =: 250
CURLOPT_PROXY_TLSAUTH_USERNAME =: 10251
CURLOPT_PROXY_TLSAUTH_PASSWORD =: 10252
CURLOPT_PROXY_TLSAUTH_TYPE =: 10253
CURLOPT_PROXY_SSLCERT =: 10254
CURLOPT_PROXY_SSLCERTTYPE =: 10255
CURLOPT_PROXY_SSLKEY =: 10256
CURLOPT_PROXY_SSLKEYTYPE =: 10257
CURLOPT_PROXY_KEYPASSWD =: 10258
CURLOPT_PROXY_SSL_CIPHER_LIST =: 10259
CURLOPT_PROXY_CRLFILE =: 10260
CURLOPT_PROXY_SSL_OPTIONS =: 261
CURLOPT_PRE_PROXY =: 10262
CURLOPT_PROXY_PINNEDPUBLICKEY =: 10263
CURLOPT_ABSTRACT_UNIX_SOCKET =: 10264
CURLOPT_SUPPRESS_CONNECT_HEADERS =: 265
CURLOPT_REQUEST_TARGET =: 10266
CURLOPT_SOCKS5_AUTH =: 267
CURLOPT_SSH_COMPRESSION =: 268
CURLOPT_MIMEPOST =: 10269
CURLOPT_TIMEVALUE_LARGE =: 30270
CURLOPT_HAPPY_EYEBALLS_TIMEOUT_MS =: 271
CURLOPT_RESOLVER_START_FUNCTION =: 20272
CURLOPT_RESOLVER_START_DATA =: 10273
CURLOPT_HAPROXYPROTOCOL =: 274
CURLOPT_DNS_SHUFFLE_ADDRESSES =: 275
CURLOPT_TLS13_CIPHERS =: 10276
CURLOPT_PROXY_TLS13_CIPHERS =: 10277
CURLOPT_DISALLOW_USERNAME_IN_URL =: 278
CURLOPT_DOH_URL =: 10279
CURLOPT_UPLOAD_BUFFERSIZE =: 280
CURLOPT_UPKEEP_INTERVAL_MS =: 281
CURLOPT_CURLU =: 10282
CURLOPT_TRAILERFUNCTION =: 20283
CURLOPT_TRAILERDATA =: 10284
CURLOPT_HTTP09_ALLOWED =: 285
CURLOPT_ALTSVC_CTRL =: 286
CURLOPT_ALTSVC =: 10287
CURLOPT_MAXAGE_CONN =: 288
CURLOPT_SASL_AUTHZID =: 10289
CURLOPT_MAIL_RCPT_ALLLOWFAILS =: 290
CURLOPT_SSLCERT_BLOB =: 40291
CURLOPT_SSLKEY_BLOB =: 40292
CURLOPT_PROXY_SSLCERT_BLOB =: 40293
CURLOPT_PROXY_SSLKEY_BLOB =: 40294
CURLOPT_ISSUERCERT_BLOB =: 40295
CURLOPT_PROXY_ISSUERCERT =: 10296
CURLOPT_PROXY_ISSUERCERT_BLOB =: 40297
CURLOPT_SSL_EC_CURVES =: 10298
CURLOPT_HSTS_CTRL =: 299
CURLOPT_HSTS =: 10300
CURLOPT_HSTSREADFUNCTION =: 20301
CURLOPT_HSTSREADDATA =: 10302
CURLOPT_HSTSWRITEFUNCTION =: 20303
CURLOPT_HSTSWRITEDATA =: 10304
CURLOPT_AWS_SIGV4 =: 10305
CURLOPT_DOH_SSL_VERIFYPEER =: 306
CURLOPT_DOH_SSL_VERIFYHOST =: 307
CURLOPT_DOH_SSL_VERIFYSTATUS =: 308
CURLOPT_CAINFO_BLOB =: 40309
CURLOPT_PROXY_CAINFO_BLOB =: 40310
CURLOPT_SSH_HOST_PUBLIC_KEY_SHA256 =: 10311
CURLOPT_PREREQFUNCTION =: 20312
CURLOPT_PREREQDATA =: 10313
CURLOPT_MAXLIFETIME_CONN =: 314
CURLOPT_MIME_OPTIONS =: 315
CURLOPT_SSH_HOSTKEYFUNCTION =: 20316
CURLOPT_SSH_HOSTKEYDATA =: 10317
CURLOPT_PROTOCOLS_STR =: 10318
CURLOPT_REDIR_PROTOCOLS_STR =: 10319
CURLOPT_WS_OPTIONS =: 320
CURLOPT_CA_CACHE_TIMEOUT =: 321
CURLOPT_QUICK_EXIT =: 322
CURLOPT_HAPROXY_CLIENT_IP =: 10323

NB. curl error codes
  CURLE_OK=: 0
  CURLE_UNSUPPORTED_PROTOCOL=:   1 
  CURLE_FAILED_INIT=:            2 
  CURLE_URL_MALFORMAT=:          3 
  CURLE_NOT_BUILT_IN=:           4 
                               
  CURLE_COULDNT_RESOLVE_PROXY=:  5 
  CURLE_COULDNT_RESOLVE_HOST=:   6 
  CURLE_COULDNT_CONNECT=:        7 
  CURLE_WEIRD_SERVER_REPLY=:     8 
  CURLE_REMOTE_ACCESS_DENIED=:   9 
                                   
                                    
  CURLE_FTP_ACCEPT_FAILED=:      10 
                                    
  CURLE_FTP_WEIRD_PASS_REPLY=:   11 
  CURLE_FTP_ACCEPT_TIMEOUT=:     12 
                                    
    
  CURLE_FTP_WEIRD_PASV_REPLY=:   13 
  CURLE_FTP_WEIRD_227_FORMAT=:   14 
  CURLE_FTP_CANT_GET_HOST=:      15 
  CURLE_HTTP2=:                  16 
  CURLE_FTP_COULDNT_SET_TYPE=:   17 
  CURLE_PARTIAL_FILE=:           18 
  CURLE_FTP_COULDNT_RETR_FILE=:  19 
  CURLE_OBSOLETE20=:             20  NB. NOT USED 
  CURLE_QUOTE_ERROR=:            21  NB. quote command failure 
  CURLE_HTTP_RETURNED_ERROR=:    22 
  CURLE_WRITE_ERROR=:            23 
  CURLE_OBSOLETE24=:             24  NB. NOT USED 
  CURLE_UPLOAD_FAILED=:          25  NB. failed upload "command" 
  CURLE_READ_ERROR=:             26  NB. could not open/read from file 
  CURLE_OUT_OF_MEMORY=:          27 
  CURLE_OPERATION_TIMEDOUT=:     28  NB. the timeout time was reached 
  CURLE_OBSOLETE29=:             29  NB. NOT USED 
  CURLE_FTP_PORT_FAILED=:        30  NB. FTP PORT operation failed 
  CURLE_FTP_COULDNT_USE_REST=:   31  NB. the REST command failed 
  CURLE_OBSOLETE32=:             32  NB. NOT USED 
  CURLE_RANGE_ERROR=:            33  NB. RANGE "command" did not work 
  CURLE_OBSOLETE34=:             34 
  CURLE_SSL_CONNECT_ERROR=:      35  NB. wrong when connecting with SSL 
  CURLE_BAD_DOWNLOAD_RESUME=:    36  NB. could not resume download 
  CURLE_FILE_COULDNT_READ_FILE=: 37 
  CURLE_LDAP_CANNOT_BIND=:       38 
  CURLE_LDAP_SEARCH_FAILED=:     39 
  CURLE_OBSOLETE40=:             40  NB. NOT USED 
  CURLE_OBSOLETE41=:             41  NB. NOT USED starting with 7.53.0 
  CURLE_ABORTED_BY_CALLBACK=:    42 
  CURLE_BAD_FUNCTION_ARGUMENT=:  43 
  CURLE_OBSOLETE44=:             44  NB. NOT USED 
  CURLE_INTERFACE_FAILED=:       45  NB. CURLOPT_INTERFACE failed 
  CURLE_OBSOLETE46=:             46  NB. NOT USED 
  CURLE_TOO_MANY_REDIRECTS=:     47  NB. catch endless re-direct loops 
  CURLE_UNKNOWN_OPTION=:         48  NB. User specified an unknown option 
  CURLE_SETOPT_OPTION_SYNTAX=:   49  NB. Malformed setopt option 
  CURLE_OBSOLETE50=:             50  NB. NOT USED 
  CURLE_OBSOLETE51=:             51  NB. NOT USED 
  CURLE_GOT_NOTHING=:            52  NB. when this is a specific error 
  CURLE_SSL_ENGINE_NOTFOUND=:    53  NB. SSL crypto engine not found 
  CURLE_SSL_ENGINE_SETFAILED=:   54  NB. can not set SSL crypto engine as default
                                    
  CURLE_SEND_ERROR=:             55  NB. failed sending network data 
  CURLE_RECV_ERROR=:             56  NB. failure in receiving network data 
  CURLE_OBSOLETE57=:             57  NB. NOT IN USE 
  CURLE_SSL_CERTPROBLEM=:        58  NB. problem with the local certificate 
  CURLE_SSL_CIPHER=:             59  NB. could not use specified cipher 
  CURLE_PEER_FAILED_VERIFICATION=:  60  NB. peer's certificate or fingerprint was not verified fine
                                      
  CURLE_BAD_CONTENT_ENCODING=:   61  NB. Unrecognized/bad encoding 
  CURLE_OBSOLETE62=:             62  NB. NOT IN USE since 7.82.0 
  CURLE_FILESIZE_EXCEEDED=:      63  NB. Maximum file size exceeded 
  CURLE_USE_SSL_FAILED=:         64  NB. Requested FTP SSL level failed 
  CURLE_SEND_FAIL_REWIND=:       65  NB. Sending the data requires a rewind that failed
                                     
  CURLE_SSL_ENGINE_INITFAILED=:  66  NB. failed to initialise ENGINE 
  CURLE_LOGIN_DENIED=:           67  NB. user, password or similar was not accepted and we failed to login
                                     
  CURLE_TFTP_NOTFOUND=:          68  NB. file not found on server 
  CURLE_TFTP_PERM=:              69  NB. permission problem on server 
  CURLE_REMOTE_DISK_FULL=:       70  NB. out of disk space on server 
  CURLE_TFTP_ILLEGAL=:           71  NB. Illegal TFTP operation 
  CURLE_TFTP_UNKNOWNID=:         72  NB. Unknown transfer ID 
  CURLE_REMOTE_FILE_EXISTS=:     73  NB. File already exists 
  CURLE_TFTP_NOSUCHUSER=:        74  NB. No such user 
  CURLE_OBSOLETE75=:             75  NB. NOT IN USE since 7.82.0 
  CURLE_OBSOLETE76=:             76  NB. NOT IN USE since 7.82.0 
  CURLE_SSL_CACERT_BADFILE=:     77  NB. could not load CACERT file, missing or wrong format
                                     
  CURLE_REMOTE_FILE_NOT_FOUND=:  78  NB. remote file not found 
  CURLE_SSH=:                    79  NB. error from the SSH layer, somewhat
                                     NB. generic so the error message will be of
                                     NB. interest when this has happened 

  CURLE_SSL_SHUTDOWN_FAILED=:    80  NB. Failed to shut down the SSL connection
                                     
  CURLE_AGAIN=:                  81  NB. socket is not ready for send/recv,
                                     NB. wait till it is ready and try again (Added
                                     NB. in 7.18.2) 
  CURLE_SSL_CRL_BADFILE=:        82  NB. could not load CRL file, missing or wrong format (Added in 7.19.0)
                                     
  CURLE_SSL_ISSUER_ERROR=:       83  NB. Issuer check failed.  (Added in 7.19.0)
                                     
  CURLE_FTP_PRET_FAILED=:        84  NB. a PRET command failed 
  CURLE_RTSP_CSEQ_ERROR=:        85  NB. mismatch of RTSP CSeq numbers 
  CURLE_RTSP_SESSION_ERROR=:     86  NB. mismatch of RTSP Session Ids 
  CURLE_FTP_BAD_FILE_LIST=:      87  NB. unable to parse FTP file list 
  CURLE_CHUNK_FAILED=:           88  NB. chunk callback reported error 
  CURLE_NO_CONNECTION_AVAILABLE=:  89  NB. No connection available, the session will be queued
                                     
  CURLE_SSL_PINNEDPUBKEYNOTMATCH=:  90  NB. specified pinned public key did not match
                                      
  CURLE_SSL_INVALIDCERTSTATUS=:  91  NB. invalid certificate status 
  CURLE_HTTP2_STREAM=:           92  NB. stream error in HTTP/2 framing layer
                                    
  CURLE_RECURSIVE_API_CALL=:     93  NB. an api function was called from inside a callback
                                     
  CURLE_AUTH_ERROR=:             94  NB. an authentication function returned an error
                                   
  CURLE_HTTP3=:                  95  NB. An HTTP/3 layer problem 
  CURLE_QUIC_CONNECT_ERROR=:     96  NB. QUIC connection error 
  CURLE_PROXY=:                  97  NB. proxy handshake error 
  CURLE_SSL_CLIENTCERT=:         98  NB. client-side certificate required 
  CURLE_UNRECOVERABLE_POLL=:     99  NB. poll/select returned fatal error 
  CURLE_TOO_LARGE=:              100  NB. a value/data met its maximum 
  CURLE_ECH_REQUIRED=:           101  NB. ECH tried but failed 
  CURL_LAST=:                    102  NB. never use! 


NB. CURLINFO constants generated by chatgpt based on code from curl.h
NB. this was from code github and may not necessarily be in sync with 
NB. the libcurl currently running on the Mac installed from homebrew
CURLINFO_NONE =: 0
CURLINFO_EFFECTIVE_URL =: 16b100001
CURLINFO_RESPONSE_CODE =: 16b200002
CURLINFO_TOTAL_TIME =: 16b300003
CURLINFO_NAMELOOKUP_TIME =: 16b300004
CURLINFO_CONNECT_TIME =: 16b300005
CURLINFO_PRETRANSFER_TIME =: 16b300006
CURLINFO_SIZE_UPLOAD =: 16b300007
CURLINFO_SIZE_UPLOAD_T =: 16b600007
CURLINFO_SIZE_DOWNLOAD =: 16b300008
CURLINFO_SIZE_DOWNLOAD_T =: 16b600008
CURLINFO_SPEED_DOWNLOAD =: 16b300009
CURLINFO_SPEED_DOWNLOAD_T =: 16b600009
CURLINFO_SPEED_UPLOAD =: 16b30000a
CURLINFO_SPEED_UPLOAD_T =: 16b60000a
CURLINFO_HEADER_SIZE =: 16b20000b
CURLINFO_REQUEST_SIZE =: 16b20000c
CURLINFO_SSL_VERIFYRESULT =: 16b20000d
CURLINFO_FILETIME =: 16b20000e
CURLINFO_FILETIME_T =: 16b60000e
CURLINFO_CONTENT_LENGTH_DOWNLOAD =: 16b30000f
CURLINFO_CONTENT_LENGTH_DOWNLOAD_T =: 16b60000f
CURLINFO_CONTENT_LENGTH_UPLOAD =: 16b300010
CURLINFO_CONTENT_LENGTH_UPLOAD_T =: 16b600010
CURLINFO_STARTTRANSFER_TIME =: 16b300011
CURLINFO_CONTENT_TYPE =: 16b100012
CURLINFO_REDIRECT_TIME =: 16b300013
CURLINFO_REDIRECT_COUNT =: 16b200014
CURLINFO_PRIVATE =: 16b100015
CURLINFO_HTTP_CONNECTCODE =: 16b200016
CURLINFO_HTTPAUTH_AVAIL =: 16b200017
CURLINFO_PROXYAUTH_AVAIL =: 16b200018
CURLINFO_OS_ERRNO =: 16b200019
CURLINFO_NUM_CONNECTS =: 16b20001a
CURLINFO_SSL_ENGINES =: 16b40001b
CURLINFO_COOKIELIST =: 16b40001c
CURLINFO_LASTSOCKET =: 16b20001d
CURLINFO_FTP_ENTRY_PATH =: 16b10001e
CURLINFO_REDIRECT_URL =: 16b10001f
CURLINFO_PRIMARY_IP =: 16b100020
CURLINFO_APPCONNECT_TIME =: 16b300021
CURLINFO_CERTINFO =: 16b400022
CURLINFO_CONDITION_UNMET =: 16b200023
CURLINFO_RTSP_SESSION_ID =: 16b100024
CURLINFO_RTSP_CLIENT_CSEQ =: 16b200025
CURLINFO_RTSP_SERVER_CSEQ =: 16b200026
CURLINFO_RTSP_CSEQ_RECV =: 16b200027
CURLINFO_PRIMARY_PORT =: 16b200028
CURLINFO_LOCAL_IP =: 16b100029
CURLINFO_LOCAL_PORT =: 16b20002a
CURLINFO_TLS_SESSION =: 16b40002b
CURLINFO_ACTIVESOCKET =: 16b50002c
CURLINFO_TLS_SSL_PTR =: 16b40002d
CURLINFO_HTTP_VERSION =: 16b20002e
CURLINFO_PROXY_SSL_VERIFYRESULT =: 16b20002f
CURLINFO_PROTOCOL =: 16b200030
CURLINFO_SCHEME =: 16b100031
CURLINFO_TOTAL_TIME_T =: 16b600032
CURLINFO_NAMELOOKUP_TIME_T =: 16b600033
CURLINFO_CONNECT_TIME_T =: 16b600034
CURLINFO_PRETRANSFER_TIME_T =: 16b600035
CURLINFO_STARTTRANSFER_TIME_T =: 16b600036
CURLINFO_REDIRECT_TIME_T =: 16b600037
CURLINFO_APPCONNECT_TIME_T =: 16b600038
CURLINFO_RETRY_AFTER =: 16b600039
CURLINFO_EFFECTIVE_METHOD =: 16b10003a
CURLINFO_PROXY_ERROR =: 16b20003b
CURLINFO_REFERER =: 16b10003c
CURLINFO_CAINFO =: 16b10003d
CURLINFO_CAPATH =: 16b10003e
CURLINFO_XFER_ID =: 16b60003f
CURLINFO_CONN_ID =: 16b600040
CURLINFO_QUEUE_TIME_T =: 16b600041
CURLINFO_USED_PROXY =: 16b200042
CURLINFO_POSTTRANSFER_TIME_T =: 16b600043
CURLINFO_EARLYDATA_SENT_T =: 16b600044
CURLINFO_HTTPAUTH_USED =: 16b200045
CURLINFO_PROXYAUTH_USED =: 16b200046
CURLINFO_LASTONE =: 70

NB. ---- CODE ----

NULL =: <0

3 : 0''
select. UNAME
 case. 'Win' do.
  LIBCURL=: '"C:\Users\Thomas\Downloads\libcurl.dll" '
 case. 'Darwin' do.
  LIBCURL=: '/opt/homebrew/Cellar/curl/8.15.0/lib/libcurl.dylib'
  LIBJCURL=: jpath '~/cppdev/jcurl/libjcurl.dylib'
 case. 'Linux' do.
  LIBCURL=: 'libcurl.dll '
 case. do.
  LIBCURL=: 'libcurl.dll '
 end.
)

NB. some usage
NB. curl_global_init(CURL_GLOBAL_DEFAULT)
NB. all pointer parameters and return values use * or *c as the 
NB. case may be. As suggested by Henry Rich
curl_global_init =: (LIBCURL,' curl_global_init n i') & cd
curl_global_cleanup =: (LIBCURL,' curl_global_cleanup n') & cd
curl_easy_init=: (LIBCURL,' curl_easy_init * ') & cd
curl_easy_cleanup=: (LIBCURL,' curl_easy_cleanup n * ') & cd

NB. multiple call signatures to the same curl_easy_setopt
NB. as suggested by Bill Lam
curl_easy_setopt_str=: (LIBCURL,' curl_easy_setopt n * i *c') & cd
curl_easy_setopt_ptr=: (LIBCURL,' curl_easy_setopt n * i *') & cd
curl_easy_setopt_int=: (LIBCURL,' curl_easy_setopt n * i i') & cd

curl_easy_perform=: (LIBCURL,' curl_easy_perform i * ') & cd

NB. not used yet but it's used for setting up header parameters
NB. to be used by curl_easy_perform in the http request
curl_slist_append=: (LIBCURL,' curl_slist_append * * *') & cd
curl_slist_free_all=: (LIBCURL,' curl_slist_free_all n *') & cd


runCurl =: 3 : 0
url =: y
curlverbose =: 1
curl_global_init <CURL_GLOBAL_DEFAULT

Cret =: curl_easy_init''
echo Cret
C =: {.Cret
echo C

if. C = 0 do. 
  NULL
  return.
end.

NB. get the C write callback and data ptr
hlibjcurl =: (15!:20) LIBJCURL
mycbp =: hlibjcurl (15!:21) 'write_callback'
chunkp =: hlibjcurl (15!:21) 'chunk'

curl_easy_setopt_str C;CURLOPT_URL;url
NB. curl_easy_setopt_ptr C;CURLOPT_URL;<<mystr
curl_easy_setopt_int C;CURLOPT_VERBOSE;1
NB. curl_easy_setopt_ptr C;CURLOPT_WRITEFUNCTION;<<mycbp
NB. curl_easy_setopt_ptr C;CURLOPT_WRITEDATA;<<chunkp

fullres =: curl_easy_perform <C
res =: >{. fullres
if. res ~: CURLE_OK do. 
  echo 'curl error'
  res
  return.
end.

respptr =. memr chunkp,0,1,JINT
respstr =. memr respptr,0,_1,JCHAR

echo respstr

curl_easy_cleanup <C

NB. close the handle to the DLL
(15!:22) hlibjcurl

respstr

curl_global_cleanup ''
)
